//AUTH
export const AUTH = 'AUTH';
export const REGISTER_STUDENT = 'REGISTER_STUDENT';
export const REGSITER_TEACHER = 'REGSITER_TEACHER';
export const LOGOUT = 'LOGOUT';

//STUDENT
export const GET_STUDENT = 'GET_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';

//TEACHER
export const GET_TEACHER = 'GET_TEACHER';
export const UPDATE_TEACHER = 'UPDATE_TEACHER';
export const DELETE_TEACHER = 'DELETE_TEACHER';

//COURSE
export const GET_COURSES = 'GET_COURSES';
export const REGISTER_COURSE = 'REGISTER_COURSE';

