export const GET_STUDENT = 'GET_STUDENT';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';

export const AUTH = 'AUTH';
export const REGISTER_STUDENT = 'REGISTER_STUDENT';
export const REGSITER_TEACHER = 'REGSITER_TEACHER';
export const LOGOUT = 'LOGOUT';

export const GET_TEACHER = 'GET_TEACHER';
export const UPDATE_TEACHER = 'UPDATE_TEACHER';


export const GET_ALL_STUDENT_COURSE = 'GET_ALL_STUDENT_COURSE';
export const GET_ALL_TEACHER_COURSE = 'GET_ALL_TEACHER_COURSE';
export const REGISTER_COURSE = 'REGISTER_COURSE';
export const GET_COURSES = 'GET_COURSES';
